name: "Check if Exists apps"
description: "Este action valida si la aplicación existe en GitOps"

inputs:
  gitOpsUrl: 
    description: "Url de github-integration"
    required: false
    default: "https://github-integration.andreani.com"
runs:
  using: "composite"
  steps: 
      - name: Checkout
        uses: actions/checkout@v4

